In [27]:
import numpy as np

def get_positional_encoding(max_length, d_model):    
    position = np.arange(max_length)[:, np.newaxis]
    print("position shape=",position.shape)
    print("position=",position)
    div_term = np.exp(np.arange(0, d_model, 2) * -(np.log(10000.0) / d_model))
    print("div_term shape=",div_term.shape)
    print("div_term=",div_term)
    pos_enc = np.zeros((max_length, d_model))
    print("position * div_term shape=",(position * div_term).shape)
    print("position * div_term=",(position * div_term))
    print("np.sin(position * div_term)=",np.sin(position * div_term))
    print("position * div_term *10 =",(position * div_term)*10)
    pos_enc[:, 0::2] = np.sin(position * div_term)
    pos_enc[:, 1::2] = np.cos(position * div_term)
    return pos_enc

def test1():
    max_length = 5
    d_model = 4
    pos_enc = get_positional_encoding(max_length, d_model)
    print(pos_enc.shape)
    print(pos_enc)

def test2():
    a=np.arange(5)
    print(a)
    a=np.arange(5)[:,np.newaxis]
    print(a)

test1()

position shape= (5, 1)
position= [[0]
 [1]
 [2]
 [3]
 [4]]
div_term shape= (2,)
div_term= [1.   0.01]
position * div_term shape= (5, 2)
position * div_term= [[0.   0.  ]
 [1.   0.01]
 [2.   0.02]
 [3.   0.03]
 [4.   0.04]]
np.sin(position * div_term)= [[ 0.          0.        ]
 [ 0.84147098  0.00999983]
 [ 0.90929743  0.01999867]
 [ 0.14112001  0.0299955 ]
 [-0.7568025   0.03998933]]
position * div_term *10 = [[ 0.   0. ]
 [10.   0.1]
 [20.   0.2]
 [30.   0.3]
 [40.   0.4]]
(5, 4)
[[ 0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.00999983  0.99995   ]
 [ 0.90929743 -0.41614684  0.01999867  0.99980001]
 [ 0.14112001 -0.9899925   0.0299955   0.99955003]
 [-0.7568025  -0.65364362  0.03998933  0.99920011]]


In [17]:
d_model=4
np.arange(0, d_model, 2) * -10

array([  0, -20])